Kotlin. ДЗ 01, Смирнов Игорь
zarechenskiy/kotlin-course-se19 pull request #1
Opened 2019-09-05 20:43 UTC by smirnov-i-SPbAU

Успешный сабмит: https://codeforces.com/contest/1205/submission/60141576

2019-09-09 23:49 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, мелкие замечения до **17.09 23:59**
В остальном написано хорошо!

2019-09-09 23:49 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        adjacencyList[aNode].add(Edge(aNode, bNode));
лишняя `;`

2019-09-09 23:49 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    private fun findCentroidDfs(vertexId: Int, parent: Int = -1): Pair<Boolean, Int> {
Предлагаю возвращать на пару, а что-нибудь более говорящее: например, собственный класс `CentroidSearchResult` -- это всего строчка в коде, но зато к типам Boolean/Int будет описание

2019-09-09 23:49 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +                    return Pair(centroidIsFound, value)
Пары в котлине удобно создавать используя инфиксную функцию `to`: `centroidIsFound to value`

2019-09-09 23:49 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        for (nextEdge: Edge in adjacencyList[edge.to]) {
указание типа `: Edge` кажется немного лишним (хотя это ничем не плохо, конечно)

2019-09-09 23:49 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    var neighbourId = 0
Кажется, `neighbourId` можно удалить

2019-09-10 06:57 UTC, smirnov-i-SPbAU commented
fixed

2019-09-10 16:28 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-09-10 16:28 UTC, zarechenskiy commented
ОК, 10/10

2019-09-10 16:28 UTC, closed without merging