Kotlin. ДЗ 1, Зуев Максим
zarechenskiy/kotlin-course-se19 pull request #10
Opened 2019-09-09 13:09 UTC by zuevmaxim

http://codeforces.com/contest/131/submission/60303578

2019-09-10 17:07 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, мелкие замечения до 17.09 23:59

2019-09-10 17:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    private val vertices: MutableList<Vertex> = mutableListOf()
можно просто `private val vertices = mutableListOf<Vertex>()`, чтобы не было повторения `MutableList`/`mutableList`

2019-09-10 17:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        }
Инициализацию можно произвести сразу в свойстве:
```
private val vertices = MutableList(size) { Vertex() }
```

+, если не нужен индекс, можно воспользоваться функцией `repeat`:
```
repeat(size) { ... }
```

2019-09-10 17:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        }
Можно воспользоваться вспомогательной функцией из стандартной библиотеки:
`require(id >= 0 && id < vertices.size) { "Vertex id is out of range." }`

2019-09-10 17:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        pathIds.removeAt(pathIds.size - 1)
Чтобы не запутаться в +1/-1 есть дополнение lastIndex: `pathIds.removeAt(pathIds.lastIndex)`

2019-09-10 19:48 UTC, zuevmaxim commented
Замечания исправлены

2019-09-22 20:01 UTC, zarechenskiy approved these changes
ОК 10/10

2019-09-22 20:01 UTC, closed without merging