HW1 done
zarechenskiy/kotlin-course-se19 pull request #13
Opened 2019-09-10 07:19 UTC by vladmosin

2019-09-10 07:19 UTC, vladmosin commented
https://codeforces.com/contest/59/submission/60256384

2019-09-10 23:06 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, мелкие замечения до 18.09 23:59

2019-09-10 23:06 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +import kotlin.math.atan
Внимательно: неиспользуемые ипорты => их стоит удалить

2019-09-10 23:06 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +fun getSymbolsFromString(string : String) : HashSet<Char> {
Форматирование: перед `:` для отделения типа пробел не нужен. То есть `string: String`

2019-09-10 23:06 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +fun getSymbolsFromString(string : String) : HashSet<Char> {
Лучше возвращать более общий тип `Set`:
- с точки зрения api нет привязки к конкретному `HashSet`, то есть можно вернуть в будущем что-нибудь другое, не сломав использования
- `Set` - read-only структура данных, поэтому её возвращать безопаснее

2019-09-10 23:06 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +fun getStringMissingSymbols(string: String) : ArrayList<Char> {
Так же: стоит вернуть просто `List<Char>`

2019-09-10 23:06 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +                }
Не сразу понял, что тут происходит. Кажется, проще так :)
```
if (string[i] == '?' && string[string.lastIndex - i] == '?') {
    canChooseSymbolNumber++
}
```

2019-09-10 23:06 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +                if (string[i] == '?' && string[string.length - 1 - i] == '?') {
Для `string.length - 1` есть свойство `lastIndex`: `string.lastIndex`

2019-09-16 08:26 UTC, vladmosin commented
Исправлено.

2019-09-22 20:06 UTC, zarechenskiy commented
@vladmosin А можешь указать на исправления, я никак не могу найти коммит с исправлениями :(

2019-12-08 22:50 UTC, closed without merging