Kotlin. ДЗ 1, Сурков Максим
zarechenskiy/kotlin-course-se19 pull request #14
Opened 2019-09-10 11:15 UTC by maximumSHOT-HSE

A: https://codeforces.com/contest/1211/submission/60338534
G: https://codeforces.com/contest/1211/submission/60341575

2019-09-10 23:22 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, мелкие замечения до 18.09 23:59

2019-09-10 23:22 UTC, zarechenskiy commented on src/main/kotlin/A.kt
> +    fun solve(r: IntArray): Pair<Pair<Int, Int>, Int> {
Для чего именно `IntArray`, а не список? В `readLine()!!.split(" ").map { it.toInt() }.toIntArray()` уже был создан `List<Int>`, его обычно удобнее использовать, чем массив

2019-09-10 23:22 UTC, zarechenskiy commented on src/main/kotlin/A.kt
> +    fun solve(r: IntArray): Pair<Pair<Int, Int>, Int> {
Хорошо бы использовать более информативные имена, чем `r` (тем более, что здесь это можно легко сделать). В этой домашке ещё ладно, но в следующих нужно будет за этим следить

2019-09-10 23:22 UTC, zarechenskiy commented on src/main/kotlin/A.kt
> +    fun solve(r: IntArray): Pair<Pair<Int, Int>, Int> {
Вместо `Pair<Pair<Int, Int>, Int>` предлагаю завести свой класс `ProblemResult` (ну или `Tripple`), чтобы не было пары от пары

2019-09-10 23:22 UTC, zarechenskiy commented on src/main/kotlin/A.kt
> +    println("${result.first.first} ${result.first.second} ${result.second}")
В классе `ProblemResult` сразу предлагаю переопределить `toString`, чтобы выводить результат

2019-09-10 23:22 UTC, zarechenskiy commented on src/main/kotlin/G.kt
> +    private var edges: ArrayList<Pair<Int, Int>>
Кажется, тут везде можно использовать `val`, а не `var`, предлагаю так и сделать

2019-09-10 23:22 UTC, zarechenskiy commented on src/main/kotlin/G.kt
> +        arcs = Array(vertexNumber) { TreeSet<Int>() }
Предлагаю перенести инициализацию сразу на декларацию `arcs` и пометить `arcs` как `val`:
```
private val arcs = Array(vertexNumber) { TreeSet<Int>() }
```

2019-09-10 23:22 UTC, zarechenskiy commented on src/main/kotlin/G.kt
> +        val path = LinkedList<Int>()
`LinkedList`? 🤔

2019-09-11 09:57 UTC, maximumSHOT-HSE commented on src/main/kotlin/A.kt
> +    fun solve(r: IntArray): Pair<Pair<Int, Int>, Int> {
Думалось, что массив должен быть быстрее, однако resubmit показал обратное.

2019-09-11 10:21 UTC, maximumSHOT-HSE commented on src/main/kotlin/G.kt
> +        arcs = Array(vertexNumber) { TreeSet<Int>() }
Видиимо сбило с толку название метода `initArcs`. Дело в том, что `arcs` перестраиваются несколько раз. Изменил название метода.

2019-09-11 10:22 UTC, maximumSHOT-HSE commented on src/main/kotlin/G.kt
> +        val path = LinkedList<Int>()
Не понял проблемы.

2019-09-11 10:28 UTC, maximumSHOT-HSE commented on src/main/kotlin/A.kt
> +    fun solve(r: IntArray): Pair<Pair<Int, Int>, Int> {
Почему `List<Int>` удобнее использовать, чем `IntArray`?

2019-09-11 10:34 UTC, maximumSHOT-HSE commented
@zarechenskiy поправил замечания

2019-09-22 20:11 UTC, zarechenskiy commented on src/main/kotlin/G.kt
> +        val path = LinkedList<Int>()
Обычно кажется, что `LinkedList` вносят больше проблем, можно посмотреть disadvanteges of LinkedList где-нибудь, ну и из недавнего :)

https://twitter.com/shipilev/status/1173324150611595264

2019-09-22 20:13 UTC, zarechenskiy commented on src/main/kotlin/A.kt
> +    fun solve(r: IntArray): Pair<Pair<Int, Int>, Int> {
У них более богатое API, есть разделение на read-only/mutable представления

2019-09-22 20:13 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-09-22 20:13 UTC, closed without merging