Kotlin. ДЗ 1, Гаврилов Данил
zarechenskiy/kotlin-course-se19 pull request #2
Opened 2019-09-05 22:39 UTC by FallenTurret

http://codeforces.com/contest/590/submission/60144365

2019-09-10 00:09 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, замечения до 17.09 23:59

2019-09-10 00:09 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +var epsilon: Double = 1e-7
`var` в Котлине означает, что свойство можно изменять, поэтому тут получилась глобальная изменяемая константа, это приводит к неприятным последствиям из-за потенциального неконтролируемого изменения.
Предлагаю это исправить: сделать свойство приватным, можно ещё пометить модификатором `const`:
https://kotlinlang.org/docs/reference/properties.html#compile-time-constants

2019-09-10 00:09 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +class Point(var x: Double = 0.0, var y: Double = 0.0)
Если есть возможность достаточно просто использовать `val` вместо `var`, то лучше так и делать, чтобы иметь больший контроль на кодом. Здесь предлагаю поменять `var` на `val` и везде создавать класс, используя конструктор

2019-09-10 00:09 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    return sqrt((first.x - second.x) * (first.x - second.x) + (first.y - second.y) * (first.y - second.y))
Это больше похоже на Java/C-way: создание утилитных статичных функций для вызовов через `foo(a, b)`.
На мой взгляд (и Котлин на это подталкивает) чаще проще читать вызовы вида `a.foo(b)`, так как так проще понять вложенные вызовы `foo(bar(a, b), c)` -> `a.bar(b).foo(c)`

Предлагаю эту функцию либо сделать мембером класса `Point` (и назвать distanceTo), либо сделать extension-функцией к Point: https://kotlinlang.org/docs/reference/extensions.html#extensions

2019-09-13 20:44 UTC, FallenTurret commented
http://codeforces.com/contest/590/submission/60504582

2019-09-22 19:44 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-09-22 19:44 UTC, closed without merging