Kotlin. ДЗ 1, Краснорядцева Анастасия
zarechenskiy/kotlin-course-se19 pull request #23
Opened 2019-09-12 17:27 UTC by anstkras

http://codeforces.com/contest/113/submission/60454393

2019-09-15 21:16 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, замечения до 23.09 23:59

2019-09-15 21:16 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    ADJECTIVE, NOUN, VERB, END, ERROR
Предлагаю удалить из `Gender` и `Token` свойство `ERROR`, чтобы не загрязнять API и не повторяться.
Вместо ошибки лучше использовать константу `null`. То есть, `getGender`/`getToken` будут возвращать null в случае неудачи

2019-09-15 21:16 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        return Gender.M;
Много повторяется `endsWith` с разными аргументами. Предлагаю завести функцию вроде `endsWithAnyOf`, которая принимает `vararg` строчек и возвращает результат, если какая-то из них является суффиксом слова:
```
fun String.endsWithAnyOf(vararg strs: String): Boolean { ... }
```

Затем эта и следующая функции переписываются в более лаконичном виде:
```
private fun getGender(word: String): Gender? {
    return when {
        word.endsWithAnyOf("lios", "etr", "initis") -> Gender.M
        word.endsWithAnyOf("liala", "etra", "inites") -> Gender.F
        else -> null
    }
}
```

2019-09-15 21:16 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    val gender = getGender(word = word)
Тут можно не использовать named argument, так как аргумент и так хорошо сам себя описывает. Вот если бы было что-то вроде `getGender("something")`, то тогда было бы не так понятно, чем является литерал `"something"

2019-09-15 21:16 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    if (gender == Gender.ERROR) {
Когда getGender будет возвращать `null`, то можно будет короче записывать это условие:
`getGender(word) ?: return false`

2019-09-15 21:16 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        curState = states.getOrDefault(curState, mapOf()).getOrDefault(getToken(word = word), State.NO)
Каждый раз создаётся пустая `Map`, и это точно можно объехать. Предлагаю чуть-чуть подумать и исправить это место, чтобы не было создания промежуточных коллекций

2019-09-23 18:52 UTC, anstkras commented
@zarechenskiy , замечания исправлены.

2019-09-24 07:59 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-09-24 07:59 UTC, closed without merging