Kotlin. ДЗ 01, Епифанов Владислав
zarechenskiy/kotlin-course-se19 pull request #26
Opened 2019-09-12 22:27 UTC by NeKp0T

2019-09-12 22:37 UTC, NeKpoT commented
Заходящая версия:
https://codeforces.com/contest/701/submission/60463587
А если сделать красиво с форичами, то МЛ:
https://codeforces.com/contest/701/submission/60463488

2019-09-15 21:30 UTC, zarechenskiy commented
> А если сделать красиво с форичами, то МЛ

Можно добавить модификатор `inline` к функции `doForChildren`, тогда будет проходить и второе решение. Без него, видимо, объекты под лямбду создаются в очень горячем месте

2019-09-15 21:43 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, замечения до 23.09 23:59

2019-09-15 21:43 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +fun readEdgeList(vertexNumber: Int, edgeNumber: Int): Array<MutableList<Int>> {
Лучше всё же добиться того, чтобы после прочтения нельзя было менять данные (вроде это и не нужно дальше). То есть, чтобы возвращаемый тип был `Array<List<Int>>` или `List<List<Int>`

2019-09-15 21:43 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +fun maximalRoadsLength(edgeList: Array<out List<Int>>, universities: List<Int>): Long {
Из-за ArrayStoreException ковариантные массивы (`Array<out ...>`) лучше обходить стороной, если это возможно

2019-09-15 21:43 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    constructor(edgeList: Array<out List<Int>>, universities: List<Int>) : this(edgeList, universities, IntArray(edgeList.size), BooleanArray(edgeList.size)) {
Если по факту используется только этот конструктор, то лучше его и оставить, чтобы код был чище и понятней:
```
class MaximalRoadsLengthFinder(
        private val edgeList: Array<List<Int>>,
        private val universities: List<Int>
) {
    
    private val subCount = IntArray(edgeList.size) { 1 }
    private val isUniversity = BooleanArray(edgeList.size) { false }
...
```

2019-09-16 15:10 UTC, NeKp0T commented
Действительно заходит с inline

2019-09-22 20:20 UTC, zarechenskiy approved these changes
ОК 10/10

2019-09-22 20:20 UTC, closed without merging