Kotlin. ДЗ 02, Бахвалов Павел
zarechenskiy/kotlin-course-se19 pull request #27
Opened 2019-09-21 20:55 UTC by Fatalll

2019-09-24 16:16 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, мелкие замечания до 01.10 23:59

2019-09-24 16:16 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/EvalVisitor.kt
> +        it[id]?.let { expr -> expr is T } ?: false
Кажется, эта строчка значит то же, что и `it[id] is T`

2019-09-24 16:16 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/EvalVisitor.kt
> +    private val stack = Stack<MutableMap<String, Expr>>()
В целом неплохо написано (но надо же найти что-нибудь), поэтому я бы предложил уменьшить использование мутабельных структур, добавив больше компиляторных абстракций, а именно, `Stack` здесь не иначе как `Context` текущего исполнения, а `MutableMap<String, Expr>` - это `Scope`.

Сейчас повторяется код, который добавляет исполняется во вложенном `Scope`, поэтому первое -- можно добавить функцию, которая это обрабатывает. Плюс функцию, которая кладёт новые декларации в текущий скоуп (это то, где повторяется код про `with(stack.peek())...`

Видится что-то такое:
```
class Context {
        private val stack = Stack<MutableMap<String, Expr>>()

        inline fun <T> nested(f: () -> T): T {
            stack.push(HashMap())
            val result = f()
            stack.pop()
            return result
        }
   ... 
}
```

=>
```
override fun visitBlock(ctx: ExpParser.BlockContext): ValueContext {
    return context.nested {
        var result = ValueContext.ZERO
        for (statement in ctx.statement()) {
            if (!result.last) result = visitStatement(statement)
        }
        result
    }
}
```

2019-09-24 16:16 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/EvalVisitor.kt
> +        }
Вот эти два `with(stack.peek())` стоит обобщить

2019-09-29 20:12 UTC, Fatalll commented on src/main/kotlin/ru/hse/spb/EvalVisitor.kt
> +        it[id]?.let { expr -> expr is T } ?: false
Действительно, исправил

2019-09-29 20:12 UTC, Fatalll commented on src/main/kotlin/ru/hse/spb/EvalVisitor.kt
> +    private val stack = Stack<MutableMap<String, Expr>>()
Переделал

2019-09-29 20:12 UTC, Fatalll commented on src/main/kotlin/ru/hse/spb/EvalVisitor.kt
> +        }
Сделал

2019-10-14 22:44 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-10-14 22:44 UTC, closed without merging