01-just-for-fun
zarechenskiy/kotlin-course-se19 pull request #3
Opened 2019-09-06 22:42 UTC by vvselischev

Успешная посылка: http://codeforces.com/contest/131/submission/60189250

2019-09-10 00:36 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, замечения до 17.09 23:59

2019-09-10 00:36 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        NOT_VISITED, IN_PROGRESS, FINISHED
Мелкое замечание: продакшн-продакшеном, но названия, используемые в классических алгоритмах, лучше такими и оставлять ради узнаваемости, поэтому эти имена ОК, но использовать white/gray/black тоже нормально + `DfsTraverseType` я бы поменял на `VertexState`

2019-09-10 00:36 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    private val stations: MutableMap<Int, Station> = HashMap()
Чуть-чуть лучше писать `...stations = mutableMapOf<Int, Station>()`: так короче + переносимость кода выше, `HashMap` может не присутствовать на какой-нибудь платформе, а `mutableMapOf` - часть стандартной библиотеки Котлина

2019-09-10 00:36 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    private val adjacentStations: MutableMap<Int, MutableList<Station>> = HashMap()
Аналогично

2019-09-10 00:36 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    fun addStationIfNotExist(vararg stationIds: Int) {
Кажется, эта функция всегда вызвыается от двух аргументов, предлагаю её так и оформить, либо вовсе заинлайнить

2019-09-10 00:36 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        adjacentStations[fromId]?.add(toStation!!)
А если `toStation` действительно `null`? 🤔

2019-09-10 00:36 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        markRingStationsDfs(stations.values.first())
`.first()` кидает исключение, если коллекция пустая. Надеюсь, здесь не так :)

2019-09-10 00:36 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +                .forEach { station -> distancesFromRing.putAll(getDistancesFromRingStation(station)) }
Я полностью за то, чтобы использовать приёмы из ФП, но, мне кажется, иногда это слишком уж усложняет действительно простой код. То есть, если бы тут был просто `for` + `if`, то это было бы сильно проще.
rule of thumb: простые вещи должны выражаться просто

Я даже попробовал написать сам :)
```
    fun getDistancesFromRingStations(): Map<Int, Int> {
        val stationValues = stations.values

        markRingStationsDfs(stationValues.first())

        val distancesFromRing = mutableMapOf<Int, Int>()
        for (station in stationValues) {
            if (station.onCycle) {
                distancesFromRing += getDistancesFromRingStation(station)
            }
        }
        return distancesFromRing
    }
```

2019-09-16 10:44 UTC, vvselischev commented on src/main/kotlin/ru/hse/spb/main.kt
> +        adjacentStations[fromId]?.add(toStation!!)
У меня тоже по этому месту вопрос: как в котлине принято такое проверять? Вызов addStationIfNotExist(fromId, toId) тремя строчками выше гарантирует, что такой элемент будет в мапе, поэтому заведомо невыполняющееся бросание повсеместных исключений кажется странной идеей.

2019-09-16 10:51 UTC, vvselischev commented on src/main/kotlin/ru/hse/spb/main.kt
> +        NOT_VISITED, IN_PROGRESS, FINISHED
Я и во всяких алгоритмах/олимпиадах всю жизнь так пишу... Всё-таки считаю, что название переменной должно в первую очередь отражать её смысл: когда читаешь код, проще явно видеть, что visited, что in_progress, а не производить дополнительную конвертацию из цвета.

2019-09-16 10:59 UTC, vvselischev commented on src/main/kotlin/ru/hse/spb/main.kt
> +                .forEach { station -> distancesFromRing.putAll(getDistancesFromRingStation(station)) }
Я считал дословно ровно так же, пока писал олимпиады, а не продакшен :) Теперь двухстрочный стрим кажется намного простым, потому что не нужно задумываться о том КАК оно реализовано (что-то перебираем, для каждого проверяем, если да, то делаем...), вместо чего при чтении понятно ЧТО делается (оставляем только вершины на цикле, для всех них считаем расстояния).
Ну и плюс, не знаю, как в котлине, но в джаве, по-моему, везде стримы, в питоне везде стримы, в c# и т.д. Разве что с++ отстаёт :)

2019-09-16 11:03 UTC, vvselischev commented on src/main/kotlin/ru/hse/spb/main.kt
> +        markRingStationsDfs(stations.values.first())
fixed

2019-09-16 11:04 UTC, vvselischev commented on src/main/kotlin/ru/hse/spb/main.kt
> +    private val stations: MutableMap<Int, Station> = HashMap()
fixed

2019-09-16 11:04 UTC, vvselischev commented on src/main/kotlin/ru/hse/spb/main.kt
> +    private val adjacentStations: MutableMap<Int, MutableList<Station>> = HashMap()
fixed

2019-09-16 11:04 UTC, vvselischev commented on src/main/kotlin/ru/hse/spb/main.kt
> +    fun addStationIfNotExist(vararg stationIds: Int) {
fixed

2019-09-22 19:50 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        adjacentStations[fromId]?.add(toStation!!)
Как вариант, `addStationIfNotExist` могла бы возвращать not-null объект с котоырм потом предполагается работа

2019-09-22 19:51 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-09-22 19:51 UTC, closed without merging