Kotlin, ДЗ 2, Танков Владислав
zarechenskiy/kotlin-course-se19 pull request #33
Opened 2019-09-26 01:03 UTC by TanVD

2019-11-29 12:28 UTC, zarechenskiy requested changes
Проверил, поправь пожалуйста мелкие замечания до 06.12 23:59

2019-11-29 12:28 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Context.kt
> +        return value as Int
с версии Котлина 1.3 можно не писать явный каст, он будет выводиться автоматически благодаря контрактам

2019-11-29 12:28 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Context.kt
> +data class Context(val value: Any?) {
почему `data`?

2019-11-29 12:28 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        MyLangVisitor().visitLFile(MyLangParser(BufferedTokenStream(MyLangLexer(CharStreams.fromFileName(path)))).lFile())
На мой взгляд, слишком уж большая вложенность, я бы выделил логичные части в переменные

2019-11-29 12:28 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/MixinFunctions.kt
> +    fun execute(name: String, params: Collection<Context>): Context {
`name` не используется, видимо, можно удалить, ну или тут с абстракциями что-то не то :)

2019-11-29 12:28 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/MixinFunctions.kt
> +        return Context.NONE;
можно не ставить `;`

2019-11-29 12:28 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Scope.kt
> +    fun <T> withFrame(body: () -> T): T {
я бы такую функцию пометил как `inline`, чтобы на каждый вызов не создавался класс под лямбду.

2019-11-29 20:19 UTC, TanVD commented on src/main/kotlin/ru/hse/spb/Context.kt
> +        return value as Int
Поправил, в проекте почему-то 1.2.61 стоял вообще :) Поменял на 1.3.61

2019-11-29 20:20 UTC, TanVD commented on src/main/kotlin/ru/hse/spb/Context.kt
> +data class Context(val value: Any?) {
Хм, привык так писать для классов со всеми параметрами в конструкторе. В данном случае вероятно не верно семантически

2019-11-30 14:14 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Context.kt
> +data class Context(val value: Any?) {
Может и верно, я больше к тому, что это нужно делать более осознанно :) Иначе, если вдруг станет понятно, что `data` не нужен, то убирание такого модификатора станет обратно-несовместимым изменением (без дополнительных подпрыгиваний)

2019-11-30 14:14 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-11-30 14:14 UTC, closed without merging