Kotlin. ДЗ 2, Вальчук Дмитрий
zarechenskiy/kotlin-course-se19 pull request #34
Opened 2019-09-26 14:30 UTC by ValchukDmitry

2019-11-29 12:41 UTC, zarechenskiy requested changes
Проверил, поправь пожалуйста замечания до 06.12 23:59

2019-11-29 12:41 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    val lexer = FunInterpreterLexer(CharStreams.fromString(program))
см. [требования](https://github.com/zarechenskiy/kotlin-course-se19/tree/02-fun-interpreter#%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8):

> Функция main должна интерпретировать файл, имя которого передано в первом аргументе

2019-11-29 12:41 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/State.kt
> +class State(val parentState: State?) {
`private val parentState`

2019-11-29 12:41 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/State.kt
> +    constructor() : this(null) {
Можно избавиться от этого конструктора, воспользовавшись значениями по умолчанию:
```
class State(val parentState: State? = null) {
...
}
```

2019-11-29 12:41 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/State.kt
> +    private val functions: MutableMap<String, Function<Int>> = mutableMapOf()
чуть короче будет, если типовые аргументы писать в функции, так не будет по 2 раза повторяться `mutableMap`:
```
private val variables = mutableMapOf<String, Int>()
private val functions = mutableMapOf<String, Function<Int>>()
```

2019-11-29 12:41 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/State.kt
> +        }
Тут `get`/`set` тривиальны: их в таком же виде генерирует и сам компилятор, поэтому их можно не писать:
```
var isReturned: Boolean = false
var returnValue: Int? = null
```

2019-11-29 12:41 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/State.kt
> +        if (variables.contains(name)) {
незначительное замечание: можно также писать `name in variables` (на мой взгляд, чуть красивее)

2019-11-29 12:41 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/StatementsEvaluatorVisitor.kt
> +    }
я не любитель init блоков, так как они разносят декларацию с реализацией, поэтому если можно, то лучше их не писать. Конкретно здесь можно написать так:
```
private var curState = State().apply { funcs.forEach { addFunc(it.key, it.value) } }
```

2019-11-29 12:41 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/StatementsEvaluatorVisitor.kt
> +    private inline fun lineNumberString(ctx: ParserRuleContext): String {
Тут модификатор `inline`, кажется, особо не нужен

2019-12-02 12:20 UTC, ValchukDmitry commented
исправил все замечания

2019-12-02 12:25 UTC, zarechenskiy approved these changes
OK, 9/10, мелкие замечания + требование про main

2019-12-02 12:26 UTC, closed without merging