Kotlin. ДЗ 2, Сурков Максим
zarechenskiy/kotlin-course-se19 pull request #35
Opened 2019-09-26 16:44 UTC by maximumSHOT-HSE

2019-09-26 16:45 UTC, maximumSHOT-HSE commented
@zarechenskiy

2019-11-29 15:07 UTC, zarechenskiy requested changes
Проверил, поправь пожалуйста мелкие замечания до 06.12 23:59

2019-11-29 15:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    val code = removeComments(File(args[0]).readLines()).joinToString(separator = System.lineSeparator())
Ход хитрый, но в реальности, кажется, не совсем хороший, так как без комментариев сообщения об ошибках будут показываться для других строчек, что будет ломать мозг :)
(исправлять это не нужно)

2019-11-29 15:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/StatementVisitor.kt
> +    }
```
class StatementVisitor() : LangBaseVisitor<Void?>() {

    private var context = ExecutionContext()

    constructor(context: ExecutionContext) : this() {
        this.context = context
    }
...
```

Можно заменить на
```
class StatementVisitor(private var context: ExecutionContext = ExecutionContext())
...
```

2019-11-29 15:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/StatementVisitor.kt
> +        check(context.varAddresses.containsKey(name)) {
несущественное замечание: тут можно также написать `name in context.varAddresses` (на мой взгляд, чуть красивее)

2019-11-29 15:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/StatementVisitor.kt
> +    override fun visitAssignment(ctx: LangParser.AssignmentContext?): Void? {
на самом деле, тип параметра здесь может быть not-null: `LangParser.AssignmentContext`. Nullable он стал, так как идея консервативно превращает типы из Java в nullable. Тоже самое для других функциях

2019-11-29 15:07 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/ExecutionContext.kt
> +data class ExecutionContext(
почему `data`?

2019-12-02 16:30 UTC, maximumSHOT-HSE commented on src/main/kotlin/ru/hse/spb/ExecutionContext.kt
> +data class ExecutionContext(
И правда многовато функциональности для `data` класса.

2019-12-02 16:31 UTC, maximumSHOT-HSE commented
@zarechenskiy fixed.

2019-12-03 06:45 UTC, zarechenskiy approved these changes
OK, 10/10

2019-12-03 06:45 UTC, closed without merging