Kotlin. ДЗ 02, Разумова Дарья
zarechenskiy/kotlin-course-se19 pull request #39
Opened 2019-09-26 19:20 UTC by Shasha33

Заранее извиняюсь

2019-11-29 16:04 UTC, zarechenskiy requested changes
Проверил, поправь пожалуйста замечания до 06.12 23:59

2019-11-29 16:04 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +import kotlin.reflect.full.declaredMemberProperties
unused import

2019-11-29 16:04 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        if (variables.containsKey(name)) {
несущественно: также можно писать `name in variables` (на мой взгляд, чуть красивее)

2019-11-29 16:04 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        parent?.rewriteVariable(name, value) ?: throw IllegalArgumentException()
кидать исключения без сообщения очень не рекомендуется, чтение таких стектрейсов никогда не приносило мне радости :)

2019-11-29 16:04 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        require(findFunction(name) == null)
так же стоит добавить сообщение к исключению

2019-11-29 16:04 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +                ctx.expression()).filterNotNull()
вместо `listOf(...).filterNotNull()` можно писать просто `listOfNotNull(...)`

2019-11-29 16:04 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +                ctx.poka(),
[:are-you-kidding-me:](https://www.google.com/search?q=are+you+kidding+me&rlz=1C5CHFA_enRU739RU740&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjOh9-n5I_mAhVPxaYKHdK0BsoQ_AUoAXoECA4QAw&biw=1440&bih=766#imgrc=6sGKLRtfRmk82M:) :)

2019-11-29 16:04 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        namespace = namespace.parent ?: throw IllegalArgumentException()
есть подозрение, что тут должен быть другой namespace:
```
val currentNamespace = namespace
namespace = namespace.extend(function, arguments)
function.blockWithBraces().accept(this)
namespace = currentNamespace ?: throw IllegalArgumentException()
```

2019-11-29 16:04 UTC, zarechenskiy commented on src/test/kotlin/ru/hse/spb/test.kt
> +        """.trimMargin())
ещё в тестах не присутствуют примеры из самого задания. Сходу у меня пример с фибоначи сломался :(

2019-12-03 10:46 UTC, Shasha33 commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        namespace = namespace.parent ?: throw IllegalArgumentException()
Наверное, я не понимаю. Во время вызова `namespace.extend` изначальный неймспейс сохраняется как родитель нового, то есть произойдет то же самое.

2019-12-03 14:39 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        namespace = namespace.parent ?: throw IllegalArgumentException()
Да, тут я неправ, извините

2019-12-03 14:40 UTC, zarechenskiy approved these changes
ОК, 8/10, так как были доделки функциональности после дедлайна + мелочи

2019-12-03 14:43 UTC, closed without merging