Kotlin. ДЗ 01, Трилис Алексей
zarechenskiy/kotlin-course-se19 pull request #4
Opened 2019-09-07 09:19 UTC by trilis

https://codeforces.com/contest/131/submission/60172977

2019-09-10 00:55 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, замечения до 17.09 23:59

2019-09-10 00:55 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +    station.adjacentStations.forEach {
По стайлгайду лучше предпочитать обычный `for` к `forEach`:https://kotlinlang.org/docs/reference/coding-conventions.html#using-loops
В обычном `for` ещё работают `break`/`continue` и если вдруг они понадобятся в будущем, то нужно будет менять какой-то код (немного, но всё же)

2019-09-10 00:55 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +)
Кажется, `Station` везде создаётся от двух аргументов, а поэтому `visited` и `distanceToCircle` лучше поместить внутрь класса, как обычные свойства, это и выглядит логичнее (создавать `Station` с `visited = true` как-то странно)

2019-09-10 00:55 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +                it.distanceToCircle = currentStation.distanceToCircle!! + 1
Как-то не очень красиво, да? :) `!!`, изменяемые данные...  Не сразу понятно, что может быть null, а что нет: `it.distanceToCircle` может, а `currentStation.distanceToCircle` - нет, нужно читать код сверху, чтобы понять.
Предлагаю полностью избавиться от `distanceToCircle`. Мне кажется, будет сильно лучше, если здесь на месте создать массив/список и заполнить его результирующими значениями (если не ошибаюсь, это должно получиться очень легко сделать)

2019-09-10 11:56 UTC, trilis commented on src/main/kotlin/ru/hse/spb/main.kt
> +                it.distanceToCircle = currentStation.distanceToCircle!! + 1
С массивом получилось лучше, но нуллы и `!!` остались - мне кажется, они нужны по смыслу, потому что для некоторых станций данные посчитаны, а для некоторых ещё нет

2019-09-22 19:53 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-09-22 19:53 UTC, closed without merging