Kotlin. ДЗ 2, Куклина Мария
zarechenskiy/kotlin-course-se19 pull request #40
Opened 2019-09-26 19:34 UTC by kuklinamd

2019-11-29 16:19 UTC, zarechenskiy requested changes
Проверил, поправь пожалуйста мелкие замечания до 06.12 23:59
За тесты отдельный "+" 👍

2019-11-29 16:19 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Utils.kt
> +// Auto-formatter says it's ok, but it looks ugly for me.
Согласен, я бы тогда записал эту функцию в одру строку:
```
fun Boolean.toInt() = if (this) 1 else 0
```

2019-11-29 16:19 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/FplTree.kt
> +        override fun apply(a: Int, b: Int): Int = a * b
много повторений `override fun apply...`, этого можно избежать сделав что-то такое:
```
enum class BinaryOperation(private val operation: (Int, Int) -> Int) : BinaryOperator<Int> {
    // Arithmetic operations
    MULT({ a, b -> a * b });

    override fun apply(t: Int, u: Int): Int = operation(t, u)
...
}
```

2019-11-29 16:19 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/FplTree.kt
> +enum class BinaryOperation : BinaryOperator<Int> {
несущественно, но тут ещё можно немного от джавы отойти, если отнаследоваться от котлиновского функционального типа:
```
enum class BinaryOperation : (Int, Int) -> Int
```

2019-11-29 16:19 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/FplInterpreter.kt
> +class FplEnv(val varEnv: Env<Optional<Int>>, val funEnv: Env<Fun>) {
Для чего тут `Optional<Int>` ? Почему не просто `Int?`?

2019-11-29 16:19 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/FplInterpreter.kt
> +        if (builtins.containsKey(funCall.identifier)) {
несущественно: можно также писать `funCall.identifier in builtins`

2019-12-03 19:19 UTC, kuklinamd commented on src/main/kotlin/ru/hse/spb/FplInterpreter.kt
> +class FplEnv(val varEnv: Env<Optional<Int>>, val funEnv: Env<Fun>) {
Чтобы различать состояния, когда переменная не определена и не существует.

2019-12-08 22:46 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-12-08 22:46 UTC, closed without merging