02 fun interpreter
zarechenskiy/kotlin-course-se19 pull request #41
Opened 2019-09-26 19:48 UTC by anstkras

2019-11-30 14:27 UTC, zarechenskiy requested changes
Проверил, поправь пожалуйста мелкие замечания до 07.12 23:59, а так написано довольно чисто 👍

2019-11-30 14:27 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/anstkras/main.kt
> +        return result
Конструкция с созданием вложенного frame повторяется в паре мест, поэтому эту логику можно было бы вынести в отдельную функцию и написать что-то такое:
```
private inline fun <T> innerFrame(body: () -> T): T {
    frameContext.addNewFrame()
    val result = body()
    frameContext.removeFrame()
    return result
}

override fun visitFile(ctx: FunInterpreterParser.FileContext): Int {
    return innerFrame {
        ctx.block().accept(this)
    }
}
```

2019-11-30 14:27 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/anstkras/FrameContext.kt
> +        frames.removeAt(frames.size - 1)
`frames.size - 1` == `frames.lastIndex`

2019-11-30 14:27 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/anstkras/FrameContext.kt
> +        if (frames.last().vars.containsKey(varName)) {
можно также писать `varName in frames.last().vars` (на мой взгляд так чуть красивее)

2019-11-30 14:27 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/anstkras/FrameContext.kt
> +        }
Можно воспользоваться функцией asReversed, которая возвращает обратный "view" для списка, чтобы не пользоваться индексами:
```
for (frame in frames.asReversed()) {
    if (varName in frame.vars) {
        return frame.vars[varName]!!
    }
}
```

2019-11-30 14:27 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/anstkras/FrameContext.kt
> +        if (frames.last().functions.containsKey(funName)) {
`frames.last()` повторяется уж очень часто здесь :)
Я бы завёл свойство `lastFrame`, чтобы не писать так каждый раз
```
private val lastFrame get() = frames.last()
```
не сильно короче, конечно, но иногда удобнее

2019-12-02 13:38 UTC, anstkras commented
@zarechenskiy , замечания исправлены.

2019-12-02 13:40 UTC, zarechenskiy approved these changes
OK, 10/10

2019-12-02 13:40 UTC, closed without merging