Kotlin. ДЗ 2, Гладков Александр
zarechenskiy/kotlin-course-se19 pull request #43
Opened 2019-09-26 20:47 UTC by 123a6bcw

Простите, не успел написать нормальные тесты :(.

2019-09-27 01:49 UTC, 123a6bcw commented
Через 5 часов после дедлайна посланы тесты и фикс двух мелких багов.

2019-11-30 14:43 UTC, zarechenskiy requested changes
Проверил, поправь пожалуйста мелкие замечания до 07.12 23:59
Отдельный "+" за тесты 👍

2019-11-30 14:43 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Scope.kt
> +        if (scoped.containsKey(identifier)) {
несущественно: можно также писать `identifier in scoped` (на мой взгляд так чуть красивее)

2019-11-30 14:43 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Scope.kt
> +        return parentScope.contains(identifier, context)
тут можно воспользоваться комбинацией safe call + elvis operator:
вместо
```
if (parentScope == null) {
    return false
}

return parentScope.contains(identifier, context)
```
Можно писать 
```
return parentScope?.contains(identifier, context) ?: false
```

2019-11-30 14:43 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        scopes = oldScopes
логика с созданием вложенного scope повторяется в паре мест, поэтому предлагаю эту конструкцию вынести в отдельную функцию, чтобы писать как-то так:
```
private inline fun innerScope(body: () -> Unit) {
    val oldScopes = scopes
    scopes = Scopes(oldScopes)
    body()
    scopes = oldScopes
}

override fun visitBlockWithBraces(context: BlockWithBracesContext): Int? {
    innerScope {
        visit(context.block())
    }

    return null
}
```

2019-11-30 14:43 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        }
В таких случаях лучше выносить `return` перед `if`, чтобы не было случайного fall-through, да и это просто короче, ну и можно ещё заменить на when, чтобы не повторять `else if`
```
override fun visitNonBinaryExpression(context: NonBinaryExpressionContext): Int? {
    return when {
        context.functionCall() != null -> 
            visit(context.functionCall())
        
        context.identifier() != null -> 
            scopes.variablesScope.getScoped(context.identifier().IDENTIFIER().text, context)
        
        context.literal() != null -> 
            context.literal().LITERAL().text.toInt()
        
        else -> 
            visit(context.expression())
    }
}
```

2019-11-30 14:43 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +                }
Тут так же стоит перенести if в переменную: `operator = if ...`

2019-12-07 06:50 UTC, 123a6bcw commented on src/main/kotlin/ru/hse/spb/Scope.kt
> +        if (scoped.containsKey(identifier)) {
Done

2019-12-07 06:50 UTC, 123a6bcw commented on src/main/kotlin/ru/hse/spb/Scope.kt
> +        return parentScope.contains(identifier, context)
Done

2019-12-07 06:50 UTC, 123a6bcw commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        scopes = oldScopes
Done

2019-12-07 06:50 UTC, 123a6bcw commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +        }
Done

2019-12-07 06:50 UTC, 123a6bcw commented on src/main/kotlin/ru/hse/spb/Visitor.kt
> +                }
Done

2019-12-07 06:50 UTC, 123a6bcw commented
Поправил.

2019-12-08 22:47 UTC, zarechenskiy approved these changes
OK, 9/10 за исправления после дедлайна и мелкие замечания

2019-12-08 22:47 UTC, closed without merging