Kotlin. ДЗ 02, Олемская Александра
zarechenskiy/kotlin-course-se19 pull request #76
Opened 2019-11-03 21:49 UTC by SiERic

2019-12-01 23:46 UTC, zarechenskiy requested changes
Проверил, поправь пожалуйста мелкие замечания до 09.12 23:59

2019-12-01 23:46 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Interpreter.kt
> +                println(expression.parameters.map { evaluate(it, state).toString() }.joinToString(" "))
можно чуть упростить:
```
expression.parameters.joinToString(" ") { evaluate(it, state).toString() }
```

2019-12-01 23:46 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/Interpreter.kt
> +    when (expression) {
стоит выносить return перед if/when, чтобы избежать ошибочного fall-through
```
fun evaluate(expression: Expression, state: State): Int {
    return when (expression) {
        is FunctionCall -> {
            if (expression.identifier == "println") {
                println(expression.parameters.joinToString(" ") { evaluate(it, state).toString() })
                0
            } else {
                val function = state.getFunction(expression.identifier)
                if (function.parameters.size != expression.parameters.size) {
                    throw RuntimeException("Wrong number of arguments in function ${function.identifier} call")
                }
                val newState = state.enter()
                function.parameters.zip(expression.parameters).map { (param, expr) -> newState.registerVariable(param, evaluate(expr, state)) }
                evaluate(function.body, newState) ?: 0
            }
        }
        is BinaryExpression -> 
            expression.operator.apply(evaluate(expression.left, state), evaluate(expression.right, state))
        is Identifier -> 
            state.getVariable(expression.identifier)
        is Literal -> 
            expression.literal
    }
}
```

2019-12-01 23:46 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/AST.kt
> +    override fun equals(other: Any?): Boolean {
стоит поддерживать equals/hashCode консистентными, в данном случае может нарушиться условие о том, что если два объекта равны, то они возвращают одинаковый `hashCode`

2019-12-01 23:46 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/AST.kt
> +enum class BinaryOperator : java.util.function.BinaryOperator<Int> {
можно наследоваться и от котлиновских функциональных типов:
```
enum class BinaryOperator : (Int, Int) -> Int
```
Так меньше зависимостей на джаву, да и понятнее (на мой взгляд)

2019-12-01 23:46 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/AST.kt
> +        override fun apply(l: Int, r: Int): Int = toInt(toBool(l) || toBool(r))
много повторений `override fun apply ... `, предлагаю сделать попроще:
```
enum class BinaryOperator(private val operation: (Int, Int) -> Int) : (Int, Int) -> Int {
    MULT({ l, r -> l * r}),
    DIV({ l, r -> l / r })
    ;

    override fun invoke(l: Int, r: Int): Int = operation(l, r)
}
```

2019-12-01 23:46 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/AST.kt
> +data class Function(val identifier: String, val parameters: List<String>, val body: Block) : Statement()
почему они все `data`? :)

2019-12-04 19:09 UTC, SiERic commented on src/main/kotlin/ru/hse/spb/AST.kt
> +data class Function(val identifier: String, val parameters: List<String>, val body: Block) : Statement()
Потому что они сами умеют нормально сравниваться

2019-12-04 19:10 UTC, SiERic commented
Я, вроде, всё исправила
@zarechenskiy

2019-12-08 22:49 UTC, zarechenskiy approved these changes
ОК, 10/10

2019-12-08 22:49 UTC, closed without merging