Kotlin. ДЗ 01, Вальчук Дмитрий
zarechenskiy/kotlin-course-se19 pull request #8
Opened 2019-09-07 22:43 UTC by ValchukDmitry

http://codeforces.com/problemset/submission/590/60242569

2019-09-10 16:26 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, мелкие замечения до 17.09 23:59

2019-09-10 16:26 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +            v2.x.toDouble() + x.toDouble(),
если везде используется `.toDouble()`, то почему бы не сделать это один раз: перед вызовом конструктора `Vector2`, а сам конструктор буде принимать уже `Double`, а не `Number`?

2019-09-10 16:26 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        }
Можно чуть короче:
```
val length: Double
    get() = sqrt(x.toDouble() * x.toDouble() + y.toDouble() * y.toDouble())
```

2019-09-10 16:26 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +                 eps: Double = 0.0000001): Double {
eps выглядит как константа, предлагаю её такой и сделать. Вынести куда-нибудь, пометить как `...const val eps = 1e-7`

2019-09-10 16:26 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +                 val maxDistance: Double = 1e9) {
Так же: `minDistance`/`maxDistance` здесь, похоже, играют роль констант

2019-09-10 16:26 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +        return time
Можно заинлайнить вызов: `return binarySearch(...)`

2019-09-10 16:55 UTC, ValchukDmitry commented on src/main/kotlin/ru/hse/spb/main.kt
> +            v2.x.toDouble() + x.toDouble(),
Мне показалось, что оставить `.toDouble()` внутри этого класса лучше, чем заставлять всех "пользователей класса" писать `.toDouble()` при его создании

2019-09-22 19:57 UTC, zarechenskiy commented on src/main/kotlin/ru/hse/spb/main.kt
> +            v2.x.toDouble() + x.toDouble(),
Если работа внутри ведётся через `Double`, то лучше внутри везде `Double` и использовать. Если хочется упростить пользователям жизнь, чтобы они не писали `toDouble`, то это решается дополнительным конструктором/фабрикой, которая принимает `Number`, один раз делает `toDouble` и возвращает Vecto2.

2019-09-22 19:59 UTC, zarechenskiy approved these changes
ОК 10/10

2019-09-22 19:59 UTC, closed without merging