Kotlin. ДЗ 1, Танков Владислав
zarechenskiy/kotlin-course-se19 pull request #9
Opened 2019-09-08 18:34 UTC by TanVD

http://codeforces.com/problemset/submission/159/60277257

2019-09-10 16:38 UTC, zarechenskiy requested changes
Проверил, поправь, пожалуйста, мелкие замечения до 17.09 23:59

2019-09-10 16:38 UTC, zarechenskiy commented on src/main/kotlin/tanvd/itmo/kotlin/Main.kt
> +                newString.asSequence()
для чего asSequence?

2019-09-10 16:38 UTC, zarechenskiy commented on src/main/kotlin/tanvd/itmo/kotlin/Main.kt
> +                        }
Кажется, можно упростить конструкцию с buildString на просто:
```
newString
    .take(p)
    .filter { it != '!' }
    .joinToString(separator = "")
```

2019-09-10 16:38 UTC, zarechenskiy commented on src/main/kotlin/tanvd/itmo/kotlin/Main.kt
> +object Solver {
Дополнительный объект тут, по-моему, только увеличивает вложенность. Достаточно обойтись top-level функцией solve

2019-09-17 09:34 UTC, TanVD commented
Fixes after review added

2019-09-22 20:00 UTC, zarechenskiy approved these changes
ОК 10/10

2019-09-22 20:00 UTC, closed without merging